package com.yundaren.common.constants;

import java.util.ArrayList;
import java.util.List;

public class SeoConstants {
	public static List<String> APP_TYPES = new ArrayList<String>();
	
	static{
		APP_TYPES.add("APP开发");
		APP_TYPES.add("APP制作");
		APP_TYPES.add("APP公司");
		APP_TYPES.add("APP应用");
		APP_TYPES.add("APP软件");
		APP_TYPES.add("APP推广");
		APP_TYPES.add("APP营销");
		APP_TYPES.add("APP客户端");
		APP_TYPES.add("APP开发教程");
		APP_TYPES.add("APP手机客户端");
		APP_TYPES.add("APP软件开发");
		APP_TYPES.add("APP开发公司");
		APP_TYPES.add("APP应用软件");
		APP_TYPES.add("APP应用程序");
		APP_TYPES.add("手机APP");
		APP_TYPES.add("手机客户端");
		APP_TYPES.add("手机APP推广");
		APP_TYPES.add("手机APP营销");
		APP_TYPES.add("手机APP制作");
		APP_TYPES.add("客户端推广");
		APP_TYPES.add("手机开发");
		APP_TYPES.add("手机应用");
		APP_TYPES.add("手机APP开发");
		APP_TYPES.add("软件制作");
		APP_TYPES.add("手机软件开发");
		APP_TYPES.add("手机应用软件");
		APP_TYPES.add("手机应用开发");
		APP_TYPES.add("手机网站制作");
		APP_TYPES.add("手机APP软件");
		APP_TYPES.add("安卓APP开发");
		APP_TYPES.add("安卓软件开发");
		APP_TYPES.add("移动APP");
		APP_TYPES.add("移动APP软件");
		APP_TYPES.add("移动APP开发");
		APP_TYPES.add("安卓手机开发");
		APP_TYPES.add("企业APP制作");
		APP_TYPES.add("公司APP制作");
		APP_TYPES.add("企业APP开发");
		APP_TYPES.add("APP是什么意思");
		APP_TYPES.add("APP手机软件");
		APP_TYPES.add("android手机开发");
		APP_TYPES.add("android开发教程");
		APP_TYPES.add("android软件开发");
		APP_TYPES.add("手机客户端开发");
		APP_TYPES.add("APP客户端开发");
		APP_TYPES.add("移动互联网推广");
		APP_TYPES.add("移动互联网营销");
		APP_TYPES.add("移动客户端开发");
		APP_TYPES.add("移动APP客户端");
		APP_TYPES.add("移动APP软件开发");
		APP_TYPES.add("APP软件开发公司");
		APP_TYPES.add("APP软件开发价格");
		APP_TYPES.add("APP手机客户端开发");
		APP_TYPES.add("安卓手机软件开发");
		APP_TYPES.add("安卓手机APP开发");
		APP_TYPES.add("手机APP开发教程");
		APP_TYPES.add("手机APP软件开发");
		APP_TYPES.add("手机APP开发软件");
		APP_TYPES.add("手机APP开发工具");
		APP_TYPES.add("手机APP如何开发");
		APP_TYPES.add("手机APP开发教程");
		APP_TYPES.add("移动APP开发工具");
		APP_TYPES.add("移动APP开发软件");
		APP_TYPES.add("手机APP开发教程");
		APP_TYPES.add("手机APP开发流程");
		APP_TYPES.add("移动APP开发教程");
		APP_TYPES.add("安卓手机客户端开发");
		APP_TYPES.add("移动应用程序开发");
		APP_TYPES.add("手机应用程序开发");
		APP_TYPES.add("安卓应用开发软件");
		APP_TYPES.add("安卓手机应用开发教程");	
	}
}
